version: "2"         # required to adjust maintainability checks
plugins:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: false
exclude_patterns:
- "spec/"
- "features/"
- "db/*"
- "lib/"
- "bin/"
- "**/vendor/"